version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: estapar-postgres
    environment:
      POSTGRES_USER: estapar
      POSTGRES_PASSWORD: estapar123
      POSTGRES_DB: estapar
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U estapar"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres-data: